# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GrinCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GrinCode
  pod 'cocoa_grinwallet', :git => 'https://github.com/gottstech/cocoa_grinwallet.git', :commit => 'ec5a686234e24f3b2faeedbedf40ffbf966e427e'

  target 'GrinCode-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GrinCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

