# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GrinCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GrinCode
  # Stable 
  pod 'cocoa_grinwallet', :git => 'https://github.com/gottstech/cocoa_grinwallet.git', :commit => '34a831edc76a2e4d752e3bbe4fefe3a266d5070e'
  # Local development
  #pod 'cocoa_grinwallet', :path => '../../../../gottstech/cocoa_grinwallet'

  target 'GrinCode-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GrinCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

