// leave off @2x/@3x
const images = {
  homeHeaderLeftBtn: require('../Images/Assets/ic_transactions_24px.png'),
  homeHeaderRightBtn: require('../Images/Assets/ic_contact_24px.png'),
  icBackR: require('../Images/Assets/ic_back_R_24px.png'),
  icBackL: require('../Images/Assets/ic_back_L_24px.png'),
  icAdd: require('../Images/Assets/ic_add_24px.png'),
  icAdd2: require('../Images/Assets/ic_add_16px.png'),
  icAvatar: require('../Images/Assets/ic_avatar_24px.png'),
  icSettings: require('../Images/Assets/ic_settings_24px.png'),
  signInCheck: require('../Images/Assets/Checkbox.png'),
  signInChecked: require('../Images/Assets/Checkbox_checked.png'),
  icSearch: require('../Images/Assets/ic_search_24px.png'),
  icSendPending: require('../Images/Assets/ic_sendPending_20px.png'),
  icReceivePending: require('../Images/Assets/ic_receivePending_20px.png'),
  icSendConfirmed: require('../Images/Assets/ic_sendConfirmed_20px.png'),
  icReceiveConfirmed: require('../Images/Assets/ic_receiveConfirmed_20px.png'),
  icSendFailed: require('../Images/Assets/ic_sendFailed_20px.png'),
  icReceiveFailed: require('../Images/Assets/ic_receiveFailed_20px.png'),
  icShow: require('../Images/Assets/ic_show_24px.png'),
  icHide: require('../Images/Assets/ic_hide_24px.png'),
  icSuccessPrimary: require('../Images/Assets/ic_success_primary_48px.png'),
  ic_close: require('../Images/Assets/ic_close_24px.png'),
  IcWriteDown: require('../Images/Assets/ic_writeDown_96px.png'),
  IcBackedUp: require('../Images/Assets/ic_backedUp_96px.png'),
  IcError: require('../Images/Assets/ic_error_24px.png'),
  icConfirmed: require('../Images/Assets/ic_confirmed_24px.png'),
  icError: require('../Images/Assets/ic_error_24px.png'),
  icDelete: require('../Images/Assets/ic_delete_16px.png'),
  icReload: require('../Images/Assets/ic_reload_16px.png'),
  icEdit: require('../Images/Assets/ic_edit_16px.png'),
  icQrcode: require('../Images/Assets/ic_qrcode_24px.png'),
  icSuccessAsk: require('../Images/Assets/ic_success_ask_48px.png'),
  icSuccessSend: require('../Images/Assets/ic_success_send_48px.png')
}

export default images
