const images = {
    launch_logo: require('../images/launch_logo.png'),
    launch_smile: require('../images/launch_smile.png'),
    button_right: require('../images/button_right.png'),
    button_left: require('../images/button_left.png'),
    button_left_white: require('../images/button_left_white.png'),
    button_down: require('../images/button_down.png'),
    button_up: require('../images/button_up.png'),
    ic_contact: require('../images/ic_contact.png'),
    ic_cancel: require('../images/ic_cancel.png'),
    ic_add: require('../images/ic_add.png'),
    ic_add_white: require('../images/ic_add_white.png'),
    ic_random: require('../images/ic_random.png'),
    ic_qrcode: require('../images/ic_qrcode.png'),
    ic_link: require('../images/ic_link.png'),
    ic_delete: require('../images/ic_delete.png'),
    ic_setting: require('../images/ic_setting.png'),
    ic_search: require('../images/ic_search.png'),
    ic_dot3: require('../images/ic_dot3.png'),
    ic_process: require('../images/ic_process.png'),
    ic_v: require('../images/ic_v.png'),
    ic_v_white: require('../images/ic_v_white.png'),
    ic_edit: require('../images/ic_edit.png'),
    ic_copy: require('../images/ic_copy.png'),
};

export default images;
