# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GrinWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
  #pod 'React', :path => '../node_modules/react-native/'
  pod 'cocoa_grinwallet', :git => 'https://github.com/gottstech/cocoa_grinwallet.git', :tag => 'v1.0.5'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge',
    ]
  # Pods for GrinWallet
  #node_modules_path = '../node_modules'
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end


  target 'GrinWallet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    #pod 'TouchID', :path => '../node_modules/react-native-touch-id'

    #pod 'RNSVG', :path => '../node_modules/react-native-svg'

    #pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

    #pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'


  end

  target 'GrinWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end




