# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GrinWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
  #pod 'React', :path => '../node_modules/react-native/'
  pod 'cocoa_grinwallet', :git => 'https://github.com/gottstech/cocoa_grinwallet.git', :tag => 'v1.0.4'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'DevSupport',
        'CxxBridge',
        'RCTActionSheet',
        'RCTGeolocation',
        'RCTImage',
        'RCTNetwork',
        'RCTPushNotification',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'RCTLinkingIOS',
        'RCTAnimation'
    ]
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Pods for GrinWallet
  #node_modules_path = '../node_modules'

  target 'GrinWallet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    #pod 'TouchID', :path => '../node_modules/react-native-touch-id'

    #pod 'RNSVG', :path => '../node_modules/react-native-svg'

    #pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

    #pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  end

  target 'GrinWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


